name: Hourly Job

on:
  schedule:
    - cron: '0 * * * *'
    #- cron: '*30 5 1 * *' # 5:30 on first of every month

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
                
      - name: install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run main
        run: |
          python main.py

      - name: discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME }}
        uses: Ilshidur/action-discord@master
        with:
          args: "The hourly CRON job completed..."
