name: logging cron

on:
  push:
  schedule:
    - cron: '*/15 0 * * *' # first of every month
    #- cron: '*30 5 1 * *' # 5:30 on first of every month

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
                
      - name: install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: log runs
        run: |
          python main.py
      
      - name: commit log
        uses: EndBug/add-and-commit@v9
        with:
          add: |
          - actions_log.txt
          authour_name: ${{ github.actor }}
          ommmit_message: "Actions log updated"