name: cron_workflow

on:
  push:
  schedule:
    - cron: '5/15 0 * * *' # every 15 minute
    #- cron: '*30 5 1 * *' # 5:30 on first of every month

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
                
      - name: install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run main
        run: |
          python main.py
