name: Thursday

on:
  schedule:
    - cron: '55 12 * * THU'
    #- cron: '*30 5 1 * *' # 5:30 on first of every month

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
                
      - name: install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run main
        run: |
          python main.py

      - name: Send a request to webhook
        run: |
          RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
            "username": "PA",
            "content": "Update the budget! <@1004790342261936369>",
            "allowed_mentions": { "users": ["1004790342261936369"]}
          }' ${{ secrets.DISCORD_WEBHOOK }})
          echo "Webhook server response: $RESPONSE"