name: Discord Service

on:
  schedule:
    - cron: '*/20 * * * *'
  push:

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send a request to webhook
        run: |
          RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
            "username": "PA",
            "content": "Every 20 minutes:\n${{ github.actor }}\n${{ github.triggering_actor }}\n<@1004790342261936369>",
            "allowed_mentions": { "users": ["1004790342261936369"]}
          }' ${{ secrets.DISCORD_WEBHOOK }})
          echo "Webhook server response: $RESPONSE"