name: My test action
on: [push, pull_request]
jobs:
  My-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Black Checker
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
      - name: Action Status
        run: echo "${{github.actor}} ran this action on the ${{ github.repository }} repository. The status is... ${{ job.status }}!"
