name: My test action
on: [push, pull_request]
jobs:
  Action-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
      - run: echo "${{github.actor}} ran this action on the ${{ github.repository }} repository. The status is... ${{ job.status }}!"
