name: test

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME }}
          DISCORD_EMBEDS: ${{ toJson('{"content": "@everyone <@&role-id> <@user-id>", "allowed_mentions": { "users": ["griffinevo"]  }}') }}
        uses: Ilshidur/action-discord@master
        with:
          args: "It's time to update the budget @griffinevo"