name: On Push

on: push

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

  generate_output:
    runs-on: ubuntu-latest
    needs: setup
    outputs:
      userid: ${{ steps.out.userid}}
    steps:
      - name: generate output
        id: userid
        run: |
          echo 'outputs="Hello Rob"' >> $GITHUB_OUTPUT


  discord:
    runs-on: ubuntu-latest
    needs: generate_output
    steps:
      - name: discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME }}
          #DISCORD_EMBEDS: ${{ toJson(needs.generate_output.outputs) }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Pushed! ${{ toJson(needs.generate_output.outputs) }}"