name: On Push

on: push

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

  discord:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Pushed!"