name: Webhook on Event

on: push

jobs:
  # ID of our job
  webhook-request:
    # OS to run our job on
    runs-on: ubuntu-latest
    steps:
    - name: Send a request to webhook
      run: |
        RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
          "username": "DS",
          "content": "<@Rob Griffin> set a new Alpe du Zwift PR of 48:12 :mount_fuji:",
          "allowed_mentions": { "users": ["Rob Griffin"]}
        }' ${{ secrets.DISCORD_WEBHOOK }})
        echo "Webhook server response: $RESPONSE"