name: Reminder Service

on: 
  push:
  schedule:
    - cron: '37 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send a request to webhook
        run: |
          RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
            "username": "PA",
            "content": "${{ github.ref }} <@1004790342261936369>",
            "allowed_mentions": { "users": ["1004790342261936369"]}
          }' ${{ secrets.DISCORD_WEBHOOK }})
          echo "Webhook server response: $RESPONSE"